version: '3.3'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
  backend:
    image: antonkrasnokutsky/foodgram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    image: antonkrasnokutsky/foodgram-frontend:v1
    volumes:
      - frontend:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/
volumes:
  db_data:
  static_value:
  media_value:
  frontend: