# Generated by Django 4.2 on 2023-05-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['author', 'user'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='subscriber',
            new_name='user',
        ),
    ]
