# Generated by Django 4.2 on 2023-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipes_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
